StylesPath = .styles
MinAlertLevel = warning

# Quét file văn bản, markdown, JSON
[*.{md,txt,json}]
BasedOnStyles = Custom

# Quét HTML (giao diện web)
[*.html]
BasedOnStyles = Custom

# Quét source code TypeScript/JavaScript/React (chú ý: Vale quét string literals)
[*.{js,ts,jsx,tsx}]
BasedOnStyles = Custom
