const data = {
    "trang-chu": "https://nd-site.github.io",
    "BTVN-EN-01": "https://nd-site.github.io/video/btvn-en-01",
    "BTVN-EN-02": "https://nd-site.github.io/video/btvn-en-02",
    "BTVN-EN-03": "https://nd-site.github.io/video/btvn-en-03",
    "BTVN-EN-04": "https://nd-site.github.io/video/btvn-en-04",
    "lac-ngoai-khong-gian": "https://www.rophim.mx/xem-phim/lac-ngoai-khong-gian.Gam4bgGk",
    "lost-in-space": "https://www.rophim.mx/xem-phim/lac-ngoai-khong-gian.Gam4bgGk",
    "Canva-Sunshine-01": "https://www.canva.com/design/DAGvetfI_es/uqV1o3aT6huZrg-dEfXuAg/edit?utm_content=DAGvetfI_es&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton",
    "video-khai-truong-sunshine-01": "https://nd-site.github.io/video/khai-truong-sunshine-01",
    "video-khai-truong-sunshine-02": "https://nd-site.github.io/video/khai-truong-sunshine-02",
    "nhap-code-playtogether-vng": "https://giftcode.vnggames.com/vn/redeem/661",
    "binh-dan-hoc-vu-so": "https://binhdanhocvuso.gov.vn",
    "ChatGPT-trendtannhacthinhphong01": "https://chatgpt.com/share/68a84616-3f04-800f-aa6d-2d948bb52212",
    "ki-tu-dac-biet": "https://bietmaytinh.com/ki-tu-dac-biet",
    "khao-sat-hoc-sinh-sunshine-01-edit": "https://docs.google.com/forms/d/1eosA5Fkvo2cmK2Wn2h4oUnJ3Vv9heduBfyXgEa8E3pE/edit",
    "khao-sat-hoc-sinh-sunshine-01": "https://forms.gle/Hk8T2rtZa9fgQTSc8",
    "viustotal-kiam-tra-virus": "https://www.virustotal.com",
    "rophim-one-piece": "https://www.rophim.mx/xem-phim/one-piece-dao-hai-tac.sestHLxS",
    "DS-mau-pptx-01": "https://thcsquantoan.haiphong.edu.vn/tu-lieu-day-hoc/70-mau-tro-choi-cho-thiet-ke-bai-giang-powerpoint/ctmb/14169/11023",
};
